name: user_repository
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  firebase_api:
    path: ../firebase_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  rxdart: ^0.27.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  mockito: ^5.4.2
  test: ^1.16.8
  lints: ^2.1.1
  build_runner: ^2.0.5