name: user_repository
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  rxdart: ^0.28.0
  flutter_secure_storage: ^10.0.0-beta.4

dev_dependencies:
  mockito: ^5.4.2
  test: ^1.16.8
  lints: ^5.0.0
  build_runner: ^2.4.10
