name: rwf_architecture_boiler_plate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  routemaster: ^1.0.1
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.3

  monitoring:
    path: packages/monitoring

  key_value_storage:
    path: packages/key_value_storage

  component_library:
    path: packages/component_library

  news_api:
    path: packages/news_api

  news_repository:
    path: packages/news_repository

  domain_models:
    path: packages/domain_models

  ## Features
  #update_profile:
  #   path: packages/features/update_profile

  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
## operations
flutter_native_splash:
  #flutter pub run flutter_native_splash:create
  background_image: "assets/images/launch_background.png"
  #color: "#7EC242"
