name: sign_in
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^9.1.0
  intl: ^0.20.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.2.0
  test: ^1.16.8
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

