name: monitoring
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_dynamic_links: ^6.0.1
  firebase_analytics: ^11.0.1
  firebase_remote_config: ^5.0.1
  firebase_app_check: ^0.3.0+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.8
