name: article
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  news_repository:
    path: ../../news_repository

  url_launcher: ^6.2.2
  flutter_bloc: ^9.1.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
