arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: article_list_localizations.dart
output-class: ArticleListLocalizations
synthetic-package: false
nullable-getter: false
