name: article_list
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  news_repository:
    path: ../../news_repository

  infinite_scroll_pagination: ^4.0.0-dev.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.16.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
