arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: user_preferences_localizations.dart
output-class: UserPreferencesLocalizations
synthetic-package: false
nullable-getter: false
