name: key_value_storage
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  hive: ^2.2.3
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.10
  hive_generator: ^2.0.0
  lints: ^5.0.0
  test: ^1.16.8
