name: key_value_storage
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  path_provider: ^2.1.3

  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  build_runner: ^2.4.10
  lints: ^4.0.0
  test: ^1.16.8

  # Isar Generator from GitHub (v3 branch)
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
