name: key_value_storage
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

isar_version: &isar_version ^3.3.0 # define the version to be used

dependencies:
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version

dev_dependencies:
  build_runner: ^2.7.1

  # Isar Generator from pub.dev
  isar_community_generator: *isar_version

  lints: ^6.0.0
  test: ^1.16.8
