name: news_repository
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  news_api:
    path: ../news_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.16.8
  lints: ^4.0.0
