name: forgot_my_password
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.1.5
  intl: ^0.19.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
