name: forgot_my_password
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.16.8
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true