name: update_profile
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.0
  intl: ^0.19.0

  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
