name: profile_menu
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_bloc: ^8.1.5
  user_repository:
    path: ../../user_repository
  domain_models:
    path: ../../domain_models
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
