name: splash
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  component_library:
    path: ../../component_library
  user_repository:
    path: ../../user_repository

  flutter_bloc: ^9.1.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  rive: ^0.13.13
  equatable: ^2.0.5
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
