arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: on_boarding_localizations.dart
output-class: OnBoardingLocalizations
synthetic-package: false
nullable-getter: false
