name: on_boarding
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.16.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
