name: component_library
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.16.8
  flutter_lints: ^2.0.2

flutter:
  generate: true
  assets:
    - assets/
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/Fondamento-Regular.ttf
